version: "3.9"

name: anjab-stack

services:
  anjab-app:
    build:
      context: .
    container_name: anjab-app
    env_file:
      - .env.docker
    environment:
      - PYTHON_BIN=/usr/bin/python3
      - SOFFICE_BIN=/usr/bin/soffice
      - SOFFICE_DIR=/usr/bin
      - SYNC_LOGS_DIR=/app/storage/sync-logs
      # - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium   # aktifkan jika perlu
    ports:
      - "8087:8087"
    volumes:
      - ./storage/pdf-cache:/app/storage/pdf-cache
      - ./storage/sync-logs:/app/storage/sync-logs
      - ./storage/rekom-jf:/app/storage/rekom-jf
      - ./storage/persesjen:/app/storage/persesjen
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    network_mode: "host"
